language: php

php:
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

script:
  - ./vendor/bin/tester -o console -p php Tests/
  - ./vendor/bin/parallel-lint -e php,phpt Core Tests
  - ./vendor/bin/phpstan analyse -l max -c phpstan.neon Core/

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done